global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] ## IP Address of the localhost. Match the port to your container port
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100'] ## IP Address of the localhost
  - job_name: "chat"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["web1:3000", "web2:3000", "web3:3000"] 